### ISSUE TITLE
Pattern not recognized

### ISSUE THREAD

**Issue by mikeyounge** [razzamatazm/NFLSportScannerRenamer#1]
Thank you so much for creating this script. It is exactly what I was looking for. However, the files that I have been finding are not being recognized as matches. The patterns are below. Let me know what you think. I'm a total noob with regex. Files append .mkv to differ them from folders

sportsnet-nfl.2023.10.23.vikings.vs.49ers.uncut.1080p.web.h264
NFL.2023.10.01.Cowboys.Vs.Patriots.1080p.WEB.H264-SPORTSNET
NFL.Week.6.2023.New.England.Patriots.vs.Las.Vegas.Raiders.15.10.720pEN60fps

Also, is this recursive? Or do the files need to be on the main directory level?

I've also noticed that the team_mapping.py is inconsistent. There are some NEWORLEANS:New.England.Patriots (and similar) matches.

**Comment by mikeyounge** [comment]
Any thoughts on this? Thanks!

**Comment by razzamatazm** [comment]
Hey Mike -

Let me fiddle around with it. Can you give me a few file names to parse?

Thanks!

**Comment by mikeyounge** [comment]
The folder and file names are the same. Add .mkv to the examples in the first post and you should be set. Thanks for looking.

**Comment by razzamatazm** [comment]
okay - it should work for your file name now - just make sure to add the files to your rename directory, get them out of folders, that might confuse the process. the files should go in the root search directory.
